---
output:
  word_document:
    keep_md: yes
---
### 介绍
運程推測小游戏

在 1 ~ 100 的數中,任選一個數字作為推測運程的方法

运行结果:
當選中 60 以下的數字時,則顯示"有不順心的事嗎?那就找朋友聊聊天吧!"
當選中 60, 60 以上,70以下的數字时,則顯示"今天運程一般般,做好你自已會讓自已更開心哦~"
當選中 70, 70 以上,80 以下的數字時,則顯示"今天會遇到需要自己解決的問題哦,加油!"
當選中 80, 80 以上,90 以下的數字時, 則顯示"今天是個適宜做決定的日子哦"
當選中 90, 90 以上,100 以下的數字時,則顯示 "快出門吧!會遇到幸運的事哦"
當選中 100 時, 則顯示"運氣十足!!是個十分開心的日子哦!"

### 代码
```{r}
score <- function(x) {
  # 首先建立一個函数,其中 score 是函数名称，function 指明该对象为函数类型，x 为函数中涉及的参数，{}中的是函数的具体内容
  
  if (x > 60 & x < 70)
  "今天運程一般般,做好你自已會讓自已更開心哦~"
  # 如果 X 的值大於 60 或小於 70,則顯示今天運程一般般,做好你自已會讓自已更開心哦~
  else if (x == 60)
  "顯示今天運程一般般,做好你自已會讓自已更開心哦~"
  # 同樣,如果 X 的值等於 60,也顯示今天運程一般般,做好你自已會讓自已更開心哦~
  else if (x > 70 & x < 80)
  "今天會遇到需要自己解決的問題哦,加油!"
  # 另一種情況,如果 X 的數大於 70 或小於 80,則顯示今天會遇到需要自己解決的問題哦,加油!
  else if (x == 70)
  "今天會遇到需要自己解決的問題哦,加油"
  # 如果 X 的值等於 70,也顯示今天會遇到需要自己解決的問題哦,加油!
  else if (x == 80)
  "今天是個適宜做決定的日子哦"
  # 如果 X 的值等於 80,顯示今天是個適宜做決定的日子哦~
  else if (x > 80 & x < 90)
  "今天是個適宜做決定的日子哦~"
  # 另一種情況,如果 X 的數大於 80 或小於 90,則顯示今天是個適宜做決定的日子哦~
  else if (x == 90)
  "快出門吧!會遇到幸運的事哦"
  # 如果 X 的值等於 90,顯示快出門吧!會遇到幸運的事哦!)
  else if (x > 90 & x < 100)
  "快出門吧!會遇到幸運的事哦!"
  # 另一種情況,如果 X 的數大於 90 或小於 100,則顯示快出門吧!會遇到幸運的事哦!
  else if (x == 100)
  "運氣十足!!是個十分開心的日子哦!"
  # 如果 X 的值等於 100,顯示運氣十足!!是個十分開心的日子哦!
  else
  "有不順心的事嗎?那就找朋友聊聊天吧!"
  # 否則顯示有不順心的事嗎?那就找朋友聊聊天吧!
}
```

### 演示
```{r}
score <- function(x) {
  if (x > 60 & x < 70)
    "今天運程一般般,做好你自已會讓自已更開心哦~"
  else if (x == 60)
    "今天運程一般般,做好你自已會讓自已更開心哦~"
  else if (x > 70 & x < 80)
    "今天會遇到需要自己解決的問題哦,加油!"
  else if (x == 70)
    "今天會遇到需要自己解決的問題哦,加油"
  else if (x == 80)
    "今天是個適宜做決定的日子哦"
  else if (x > 80 & x < 90)
    "今天是個適宜做決定的日子哦~"
  else if (x == 90)
    "快出門吧!會遇到幸運的事哦"
  else if (x > 90 & x < 100)
    "快出門吧!會遇到幸運的事哦!"
  else if (x == 100)
    "運氣十足!!是個十分開心的日子哦!"
  else
    "有不順心的事嗎?那就找朋友聊聊天吧!"
}
```

